from typing import Any


class Observer:
    def schedule(self, handler: Any, path: str, recursive: bool = True) -> None: ...

    def start(self) -> None: ...

    def stop(self) -> None: ...

    def join(self, timeout: float | None = None) -> None: ...
